show databases;
use data_analyst;
select * from customer limit 20;
-- 📋 Questions
-- Q1. What is the total revenue generated by male vs. female customers?
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- Q8. What are the top 3 most purchased products within each category?
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?

-- Q1. What is the total revenue generated by male vs. female customers?
select * from customer limit 20;
select gender, sum(`purchase_amount_(usd)`) as revenue
from customer
group by gender;
-- select `purchase_amount_(usd)` from customer;
-- -------- practice -------------------------------------------------
select gender, sum(`purchase_amount_(usd)`) as revenue, discount_applied
from customer
group by gender, discount_applied;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select * from customer limit 5;
select customer_id, `purchase_amount_(usd)` 
from customer
where 
discount_applied = 'Yes' and 
`purchase_amount_(usd)` >= (select avg(`purchase_amount_(usd)`) from customer);
-- ----------practice-----------------------------
select customer_id, `purchase_amount_(usd)`
from customer
where discount_applied = 'Yes' and 
`purchase_amount_(usd)` >= (select avg(`purchase_amount_(usd)`) from customer)
limit 5;

select avg(`purchase_amount_(usd)`) from customer;
select customer_id from customer;

-- Q3. Which are the top 5 products with the highest average review rating?
select * from customer limit 5;
select item_purchased , round(avg(review_rating), 2) as avg_rating
from customer
group by item_purchased
order by avg_rating DESC limit 5;
-- practice----------------------------------------
select item_purchased, round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased  
order by avg_rating desc limit 5;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
select * from customer limit 5;
select distinct shipping_type from customer;

select shipping_type , round(avg(`purchase_amount_(usd)`),2) 
from customer
where shipping_type in ('Express' , 'Standard')
group by shipping_type;

-- Q4 - a). Compare the average purchase amounts between Free Shipping and 2-Day Shipping Shipping in descing order.
select shipping_type , round(avg(`purchase_amount_(usd)`),2) as avg_purchased_amount
from customer
-- where shipping_type in ('Free Shipping' ,'2-Day Shipping') 
group by shipping_type
order by avg_purchased_amount desc;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select * from customer limit 5;
select subscription_status, count(customer_id) as total_customer, 
avg(`purchase_amount_(usd)`) as avg_spend, 
sum(`purchase_amount_(usd)`) as total_revenue
from customer
where subscription_status in ('Yes','No') 
group by subscription_status
order by total_revenue, avg_spend;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customer limit 5;
select item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end)*100 / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
select * from customer limit 5;
select customer_id , previous_purchases,
case 
when previous_purchases < 2 then 'NEW'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as segment 
from customer
group by customer_id
order by count(segment);
-- -----------------------------------------------
-- we used a CTE common table expression - temporary table customer_type
with customer_type as (
select customer_id , previous_purchases,
case 
when previous_purchases < 2 then 'NEW'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment 
from customer
)
select customer_Segment, count(*) as 'Number_of_Customers'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
select * from customer limit 5;
-- we used rank, dense rank and row number functions to rank it.
with item_counts as (
select category, item_purchased, 
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_Rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customer limit 5;
select  subscription_status,
case
when previous_purchases > 5 
then 'Repeated Buyers' 
else 'not' 
end as repeated_buyers,
count(*) as total
from customer
group by subscription_status, repeated_buyers;
-- -----------------------------------------------------------------------------
select subscription_status , 
count(customer_id) as repeat_customer
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select * from customer limit 5;
select age_group, sum(`purchase_amount_(usd)`)  as total_revenue
from customer
group by age_group
order by total_revenue desc;

select distinct age, sum(`purchase_amount_(usd)`) as total_revenue
from customer
group by age
order by age desc, total_revenue;


